### ISSUE TITLE
请教shadowrocket问题

### ISSUE THREAD

**Issue by artcaster** [cute/DLWBouncyView#1]
您好，没有找到邮箱，不好意思在这里提问了，我已经购买了iOS版的，想请教几个问题，因为在网上没有看到相关的教程，我是这样fq的，在路由器上利用dnsmasq把域名解析到到香港的https劫持缓存服务器，比如219.76.4.4，然后通过iptables把所有访问219.76.4.4的请求走65端口，再用nginx对所有65端口的http 请求强制转跳https：这样实现了fq。具体原理在这里https://github.com/realpg/openwrt-hurdle-configuration，我知道用小火箭支持用hosts把域名解析到指定的IP，但是有两个难题，一个是小火箭的hosts是否支持通配符，比如*.googlevideo.com = 219.76.4.4这样配置是否有用，还有就是能否强制某些后缀名或者ip强制https，因为http会被截断并可能导致这些稀有的缓存服务器被拉入黑名单，非常期待您的解答，谢谢。

**Comment by artcaster** [comment]
您好，我已经购买了iOS版的，想请教几个问题，因为在网上没有看到相关的教程，我是这样fq的，在路由器上利用dnsmasq把域名解析到到香港的https劫持缓存服务器，比如219.76.4.4，然后通过iptables把所有访问219.76.4.4的请求走65端口，再用nginx对所有65端口的http 请求强制转跳https：这样实现了fq。具体原理在这里https://github.com/realpg/openwrt-hurdle-configuration，我知道用小火箭支持用hosts把域名解析到指定的IP，但是有两个难题，一个是小火箭的hosts是否支持通配符，比如*.googlevideo.com = 219.76.4.4这样配置是否有用，还有就是能否强制某些后缀名或者ip强制https，因为http会被截断并可能导致这些稀有的缓存服务器被拉入黑名单，非常期待您的解答，谢谢。

**Comment by cute** [comment]
*.googlevideo.com = 219.76.4.4这种是支持的。
目前不能http转https。
